name: flutter_db_client
description: "Open DB Client built with Flutter 💙"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  bitsdojo_window: ^0.1.6
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  icons_plus: ^5.0.0
  intl: ^0.19.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geist Mono
      fonts:
        - asset: assets/fonts/geist/mono/GeistMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/geist/mono/GeistMono-Light.ttf
          weight: 200
        - asset: assets/fonts/geist/mono/GeistMono-Medium.ttf
          weight: 300
        - asset: assets/fonts/geist/mono/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/geist/mono/GeistMono-Bold.ttf
          weight: 500
        - asset: assets/fonts/geist/mono/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/geist/mono/GeistMono-UltraLight.ttf
          weight: 700
        - asset: assets/fonts/geist/mono/GeistMono-UltraBlack.ttf
          weight: 700
        - asset: assets/fonts/geist/mono/GeistMono-Black.ttf
          weight: 900
    - family: Geist Sans
      fonts:
        - asset: assets/fonts/geist/sans/Geist-Thin.ttf
          weight: 100
        - asset: assets/fonts/geist/sans/Geist-Light.ttf
          weight: 200
        - asset: assets/fonts/geist/sans/Geist-Medium.ttf
          weight: 300
        - asset: assets/fonts/geist/sans/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/geist/sans/Geist-Bold.ttf
          weight: 500
        - asset: assets/fonts/geist/sans/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/geist/sans/Geist-UltraLight.ttf
          weight: 700
        - asset: assets/fonts/geist/sans/Geist-UltraBlack.ttf
          weight: 700
        - asset: assets/fonts/geist/sans/Geist-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
